import 'dart:convert';
import 'dart:math';
import 'package:flutter/services.dart';

/// Generates memorable usernames in the format:
///   adjective + noun + 3-digit-number
/// e.g. "boldbadger042"
class UsernameGenerator {
  static List<String> _adjectives = _initialAdjectives;
  static List<String> _nouns = _initialNouns;
  static final _random = Random();

  /// Loads username components from assets/data/username_components.json.
  /// Falls back to hardcoded lists if the file is missing or invalid.
  static Future<void> load() async {
    try {
      final jsonString = await rootBundle.loadString('assets/data/username_components.json');
      final Map<String, dynamic> data = json.decode(jsonString);
      
      if (data.containsKey('adjectives') && data['adjectives'] is List) {
        _adjectives = List<String>.from(data['adjectives']);
      }
      if (data.containsKey('nouns') && data['nouns'] is List) {
        _nouns = List<String>.from(data['nouns']);
      }
    } catch (e) {
      // ignore: avoid_print
      print('[UsernameGenerator] Failed to load JSON components: $e');
    }
  }

  /// Returns a username like "boldbadger042".
  static String generate() {
    final adj = _adjectives[_random.nextInt(_adjectives.length)];
    final noun = _nouns[_random.nextInt(_nouns.length)];
    // 3-digit number with leading zeros: 000 – 999
    final number = _random.nextInt(1000).toString().padLeft(3, '0');
    return '$adj$noun$number';
  }

  static const _initialAdjectives = [
    'absurd',
    'ancient',
    'anxious',
    'baffled',
    'bold',
    'bonkers',
    'bouncy',
    'brazen',
    'breezy',
    'brooding',
    'bumbling',
    'cagey',
    'careless',
    'cheeky',
    'chewy',
    'chunky',
    'clumsy',
    'cranky',
    'crusty',
    'cunning',
    'damp',
    'dazed',
    'devious',
    'dingy',
    'dizzy',
    'doughy',
    'dramatic',
    'droopy',
    'dubious',
    'dusty',
    'edgy',
    'elastic',
    'elusive',
    'erratic',
    'fancy',
    'feral',
    'filthy',
    'fishy',
    'flaky',
    'flimsy',
    'fluffy',
    'frantic',
    'frumpy',
    'furtive',
    'fuzzy',
    'gangly',
    'gloomy',
    'goofy',
    'greasy',
    'grumpy',
    'guilty',
    'hairy',
    'hapless',
    'hazy',
    'hefty',
    'hollow',
    'hopeless',
    'hungover',
    'idiotic',
    'irate',
    'jittery',
    'jolly',
    'jumpy',
    'lanky',
    'lazy',
    'leaky',
    'leery',
    'lumpy',
    'mangy',
    'meek',
    'melted',
    'menacing',
    'messy',
    'moody',
    'mopey',
    'muddy',
    'mysterious',
    'nervous',
    'noisy',
    'noodle',
    'odd',
    'oozy',
    'paranoid',
    'pasty',
    'peculiar',
    'petty',
    'plump',
    'pompous',
    'pouty',
    'puffy',
    'quirky',
    'reckless',
    'restless',
    'rigid',
    'rowdy',
    'rubbery',
    'runny',
    'rusty',
    'scruffy',
    'shady',
    'shaky',
    'shifty',
    'shiny',
    'silly',
    'sketchy',
    'sleazy',
    'sleepy',
    'slimy',
    'slippery',
    'sloppy',
    'sluggish',
    'sly',
    'smelly',
    'soggy',
    'solemn',
    'sour',
    'spooky',
    'squishy',
    'stale',
    'sticky',
    'stinky',
    'stubborn',
    'sulky',
    'surly',
    'sweaty',
    'tangled',
    'twitchy',
    'unhinged',
    'uptight',
    'vague',
    'vexed',
    'wacky',
    'weary',
    'whiny',
    'wiry',
    'wobbly',
    'woozy',
    'wrinkly',
    'zesty',
  ];

  static const _initialNouns = [
    'avocado',
    'badger',
    'banana',
    'biscuit',
    'blobfish',
    'bologna',
    'bonbon',
    'booger',
    'bratwurst',
    'brisket',
    'broccoli',
    'brownie',
    'buffalo',
    'bun',
    'bunny',
    'burrito',
    'cabbage',
    'cactus',
    'calzone',
    'camel',
    'casserole',
    'catfish',
    'celery',
    'cheese',
    'cheeto',
    'cheetah',
    'chicken',
    'chipmunk',
    'clam',
    'cobbler',
    'cod',
    'condor',
    'cookie',
    'crouton',
    'cucumber',
    'cupcake',
    'custard',
    'dingo',
    'dodo',
    'donut',
    'doughnut',
    'dumpling',
    'echidna',
    'eggplant',
    'ferret',
    'flamingo',
    'fritter',
    'fungus',
    'gerbil',
    'gibbon',
    'gopher',
    'gorilla',
    'gravy',
    'guinea pig',
    'hamster',
    'hedgehog',
    'hippo',
    'hotdog',
    'hyena',
    'iguana',
    'jellyfish',
    'jerky',
    'kumquat',
    'lasagna',
    'lemur',
    'linguine',
    'llama',
    'lobster',
    'macaroon',
    'manatee',
    'marmot',
    'marshmallow',
    'meatball',
    'melon',
    'mochi',
    'mole',
    'moose',
    'muffin',
    'mushroom',
    'mussel',
    'nachos',
    'narwhal',
    'noodle',
    'nugget',
    'ocelot',
    'okra',
    'orca',
    'ostrich',
    'otter',
    'oyster',
    'pancake',
    'pangolin',
    'parsnip',
    'pastry',
    'peanut',
    'pelican',
    'penguin',
    'pickle',
    'pigeon',
    'platypus',
    'possum',
    'pretzel',
    'pudding',
    'puffin',
    'quiche',
    'radish',
    'raccoon',
    'ramen',
    'rhubarb',
    'rigatoni',
    'salamander',
    'salami',
    'salmon',
    'sardine',
    'sausage',
    'scallion',
    'shrimp',
    'skunk',
    'sloth',
    'slug',
    'snail',
    'snapper',
    'squid',
    'squirrel',
    'strudel',
    'tamale',
    'tapir',
    'tardigrade',
    'toad',
    'tofu',
    'truffle',
    'tuna',
    'turkey',
    'turnip',
    'walrus',
    'waffle',
    'warthog',
    'weasel',
    'wombat',
    'yak',
    'zucchini',
  ];
}
