// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHHjfc2wGb0-ML2AoTCzxyOV9tqQZQI7Q',
    appId: '1:202267211418:android:1f4a67e05c23c05edd1123',
    messagingSenderId: '202267211418',
    projectId: 'littlewin-2fbc7',
    storageBucket: 'littlewin-2fbc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoHCDMY0VOZGl4AyW2kncYWyarGyNdmHw',
    appId: '1:202267211418:ios:905042e197d3f701dd1123',
    messagingSenderId: '202267211418',
    projectId: 'littlewin-2fbc7',
    storageBucket: 'littlewin-2fbc7.firebasestorage.app',
  );
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHHjfc2wGb0-ML2AoTCzxyOV9tqQZQI7Q',
    appId: '1:202267211418:web:placeholder', // You may need to run flutterfire configure for the real web appId
    messagingSenderId: '202267211418',
    projectId: 'littlewin-2fbc7',
    authDomain: 'littlewin-2fbc7.firebaseapp.com',
    storageBucket: 'littlewin-2fbc7.firebasestorage.app',
  );
}
